config/routes.rb
#require 'api_constraints'
Rails.application.routes.draw do
  namespace :api do
      resources :customers ,  defaults: { format: :json }
      resources :orders
      # match 'auth/authorize' => 'auth#authorize', via: :all
      # match 'auth/access_token' => 'auth#access_token', via: :all
      # match 'auth/customer' => 'auth#customer', via: :all
      
  end
  devise_for :customers, destroy_customer_session_via: [:get, :delete], controllers: { registrations: 'customers/registrations', sessions: 'customers/sessions', omniauth_callbacks: 'callbacks' }
  devise_scope :customer do
    get 'customers/sign_up/:id/show', to: 'devise/registrations#show', as: 'show_registration'
    post 'customers/sign_up/:id/show', to: 'devise/registrations#show'
  end
  use_doorkeeper do 
    skip_controllers :application, :authorized_applications
  end
  get 'welcome/index'
  #resources :customers
	resources :items
	get 'items/:id/modify', to: 'items#modify', as: 'modify_item'
	patch 'items/:id/modif', to: 'items#modif'
	post 'items/:id', to: 'items#modif'
	get 'customers/orders', to: 'orders#index', as: 'orders'
	post 'customers/orders', to: 'orders#create'
	get 'customers/orders/:id/new', to: 'orders#new', as: 'new_order'
	get 'customers/orders/:id/list', to: 'orders#list', as: 'list_order'
	get 'customers/orders/:id', to: 'orders#show', as: 'order' 
  root 'welcome#index'
  #match 'items/:id/modify', :to => 'items#modify', :as => 'modify_item',  :via => :get
	#match 'items/:id', :to => 'items#modif', via: [:patch ,:put]
	match 'auth/authorize' => 'auth#authorize', via: :all
  match 'auth/access_token' => 'auth#access_token', via: :all
  match 'auth/customer' => 'auth#customer', via: :all
  match 'oauth/token' => 'auth#access_token', via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% if customer_signed_in? %>
	Logged in as <strong><%= current_customer.email %></strong>.
  <%= link_to 'Edit profile', edit_customer_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_customer_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
<%= link_to "Sign up", new_customer_registration_path, :class => 'navbar-link'  %> |
<%= link_to "Login", new_customer_session_path, :class => 'navbar-link'  %>
<% end %>
<h1>Customer crud</h1>
<ul>

<li><%= link_to 'Item ', controller: 'items' %></li>
</ul>