config/routes.rb
#require 'api_constraints'
Rails.application.routes.draw do
  namespace :api do
      resources :customers ,  defaults: { format: :json }
      resources :orders
      # match 'auth/authorize' => 'auth#authorize', via: :all
      # match 'auth/access_token' => 'auth#access_token', via: :all
      # match 'auth/customer' => 'auth#customer', via: :all
      
  end
  devise_for :customers, destroy_customer_session_via: [:get, :delete], controllers: { registrations: 'customers/registrations', sessions: 'customers/sessions', omniauth_callbacks: 'callbacks' }
  devise_scope :customer do
    get 'customers/sign_up/:id/show', to: 'devise/registrations#show', as: 'show_registration'
    post 'customers/sign_up/:id/show', to: 'devise/registrations#show'
  end
  use_doorkeeper do 
    skip_controllers :application, :authorized_applications
  end
  get 'welcome/index'
  #resources :customers
	resources :items
	get 'items/:id/modify', to: 'items#modify', as: 'modify_item'
	patch 'items/:id/modif', to: 'items#modif'
	post 'items/:id', to: 'items#modif'
	get 'customers/orders', to: 'orders#index', as: 'orders'
	post 'customers/orders', to: 'orders#create'
	get 'customers/orders/:id/new', to: 'orders#new', as: 'new_order'
	get 'customers/orders/:id/list', to: 'orders#list', as: 'list_order'
	get 'customers/orders/:id', to: 'orders#show', as: 'order' 
  root 'welcome#index'
  #match 'items/:id/modify', :to => 'items#modify', :as => 'modify_item',  :via => :get
	#match 'items/:id', :to => 'items#modif', via: [:patch ,:put]
	match 'auth/authorize' => 'auth#authorize', via: :all
  match 'auth/access_token' => 'auth#access_token', via: :all
  match 'auth/customer' => 'auth#customer', via: :all
  match 'oauth/token' => 'auth#access_token', via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	belongs_to :item
	validate :update_item_stock
	def update_item_stock
		remaining_stock=item.stock
		item.stock-=self.quantity
		if item.stock < 0

			#self.errors.add"Stock unavailable ,try with lesser quantity"
			#validates :stock, numericality: { :greater_than_or_equal_to => 0}
			self.errors.add(:stock , " unavailable ,try with #{(remaining_stock).abs} or lesser quantity")
			return false
		else	
			item.save
		end
	end
end

app/controllers/api/orders_controller.rb
class Api::OrdersController < ApplicationController
	protect_from_forgery with: :null_session
	#before_action :destroy_session
	respond_to :json
	# def destroy_session
	# 	request.session_options[:skip] = true
	# end
	#doorkeeper_for :all
	#before_action :doorkeeper_authorize!
	#DISPLAY ALL CUSTOMERS
	def index 				
		#@customer = Customer.find(doorkeeper_token.resource_owner_id) 
		@orders=current_customer.orders
		respond_to do |format|
			format.json { render json: @orders  }
			format.xml { render file: 'show.xml.builder', content_type: "application/xml" }
			format.html { render 'customers/show' }
		end
		#super
	end

	# def show
	# 	#@customer = Customer.find(params[:id])
	# 	@orders=current_customer.orders
	# 	respond_to do |format|
	# 		format.json { render json: @orders  }
	# 		format.xml { render file: 'show.xml.builder', content_type: "application/xml" }
	# 		format.html { render 'customers/show' }
	# 	end
	# end

	def create
	#	@order=current_customer.orders
		@orders = current_customer.create(params[:@order])
		respond_to do |format|
			format.json { render json: @orders  }
			format.xml { render file: 'show.xml.builder', content_type: "application/xml" }
			format.html { render 'customers/show' }
		end
	end

	private
	def current_customer
			current_customer ||= Customer.find(doorkeeper_token.resource_owner_id)
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	#	before_action :doorkeeper_authorize!
	def index
		@order = Order.all
	end
	def show
		@order = Order.find(params[:id])
	end
	def new
		#@customer = Customer.find_by_id (params[:id])
		@order = Order.new(:customer_id => params[:id])
	end
	def list
		@customer = current_customer
		@ans= @customer.orders
		#@tmp = params[:id]
		#@orde = Order.where(:customer_id => params[:id])
		#@ans = @orde.to_a{|o| o.select(:item_id)}
		#@ans = Order.select(:item_id,:quantity).from(@orde)		
		# @orde= Order.select("item_id").where(":customer_id = ",@tmp)
		# @ans = @ords.to_a.uniq{|o| o.item_id}
		
	end
	def create
		@order = Order.new(order_params)
		@order.total_cost = @order.item.price * @order.quantity
		

		if @order.save
			redirect_to @order
		else
			render 'new'
		end
	end
	private
		def order_params
			params.require(:order).permit(:customer_id, :item_id, :quantity)
		end
		
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<h1> PAGE SHOULD BE DEPRECATED </h1>

<h1>Listing Order Details</h1>
 
 <%= link_to 'Back', customers_path %>
<%= link_to 'HOME', welcome_index_path %>
<table>
  <tr>
    <th>item id</th>
    <th>quantity</th>
    <th></th>
  </tr>
 
  <% @order.each do |order| %>
    <tr>
      <td><%= order.item_id %></td>
      <td><%= order.quantity %></td>
      <td><%= link_to 'Show', order_path(customer) %></td>

    </tr>
  <% end %>
</table>

app/views/orders/list.html.erb
<% if customer_signed_in? %>
	Logged in as <strong><%= current_customer.email %></strong>.
  <%= link_to 'Edit profile', edit_customer_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_customer_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>

<h3>Your orders</h3>
<table>
  <tr>
    <th>item id</th>
    <th>item name</th>
    <th>quantity</th>
    <th>total_cost</th>
    <th></th>
  </tr>
 
  <% @ans.each do |answ| %>
    <tr>
      <td><%= answ.item_id %></td>
      <td><%= Item.find(answ.item_id).name %></td>
      <td><%= answ.quantity %></td>
      <td><%= answ.total_cost %></td>
    </tr>
    <tr>

    </tr>
  <% end %>
</table>

<%= link_to 'Add Orders', new_order_path(current_customer) %>
<%= link_to 'view profile', show_registration_path(current_customer) %>

app/views/orders/new.html.erb
<%= form_with model: @order,
local: true do |form| %>
<% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %> prohibited
        this order from being saved:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<p>
    <%= form.hidden_field :customer_id %><br>
    <%= form.hidden_field :customer_id %>
  </p>
 
  <p>
    <%= form.label :item_id %><br>
    <%= form.collection_select(:item_id, Item.order(:id,:name), :id ,:name)  %>
  </p>
 
 <p>
    <%= form.label :quantity %><br>
    <%= form.text_field :quantity %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end%>
<%= link_to 'Back', list_order_path(current_customer) %>
  

app/views/orders/show.html.erb
<p>
  <strong>customer id:</strong>
  <%= @order.customer.name %>
</p>
 
<p>
  <strong>items:</strong>
  <%= @order.item.name %>
</p>

<p>quantity :</strong>
  <%= @order.quantity %>
</p>

<%= link_to 'Back', list_order_path(current_customer) %>