config/routes.rb
#require 'api_constraints'
Rails.application.routes.draw do
  namespace :api do
      resources :customers ,  defaults: { format: :json }
      resources :orders
      # match 'auth/authorize' => 'auth#authorize', via: :all
      # match 'auth/access_token' => 'auth#access_token', via: :all
      # match 'auth/customer' => 'auth#customer', via: :all
      
  end
  devise_for :customers, destroy_customer_session_via: [:get, :delete], controllers: { registrations: 'customers/registrations', sessions: 'customers/sessions', omniauth_callbacks: 'callbacks' }
  devise_scope :customer do
    get 'customers/sign_up/:id/show', to: 'devise/registrations#show', as: 'show_registration'
    post 'customers/sign_up/:id/show', to: 'devise/registrations#show'
  end
  use_doorkeeper do 
    skip_controllers :application, :authorized_applications
  end
  get 'welcome/index'
  #resources :customers
	resources :items
	get 'items/:id/modify', to: 'items#modify', as: 'modify_item'
	patch 'items/:id/modif', to: 'items#modif'
	post 'items/:id', to: 'items#modif'
	get 'customers/orders', to: 'orders#index', as: 'orders'
	post 'customers/orders', to: 'orders#create'
	get 'customers/orders/:id/new', to: 'orders#new', as: 'new_order'
	get 'customers/orders/:id/list', to: 'orders#list', as: 'list_order'
	get 'customers/orders/:id', to: 'orders#show', as: 'order' 
  root 'welcome#index'
  #match 'items/:id/modify', :to => 'items#modify', :as => 'modify_item',  :via => :get
	#match 'items/:id', :to => 'items#modif', via: [:patch ,:put]
	match 'auth/authorize' => 'auth#authorize', via: :all
  match 'auth/access_token' => 'auth#access_token', via: :all
  match 'auth/customer' => 'auth#customer', via: :all
  match 'oauth/token' => 'auth#access_token', via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :orders
  has_many :customers, through: :orders
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
	def index
		@item = Item.all
	end
	def show
		@item = Item.find(params[:id])
	end
	def new
		@item = Item.new
	end
	def edit
		@item = Item.find(params[:id])
	end
	def create
		@item = Item.new(item_params)

		if @item.save
			redirect_to @item
		else
			render 'new'
		end
	end
	def update
		@item = Item.find(params[:id])

		if @item.update(item_params)
			redirect_to @item
		else
			render 'edit'
		end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy

		redirect_to items_path
	end

	private
		def item_params
			params.require(:item).permit(:ino,:name,:price,:stock)
		end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	#before_action :doorkeeper_authorize!
	def index
		@item = Item.all
	end
	def show
		@item = Item.find(params[:id])
	end
	def new
		@item = Item.new
	end
	def edit
		@item = Item.find(params[:id])
	end
	def modify
		@item = Item.find(params[:id])
		#@t = @item
		#@item.increment!('stock',5)
	end
	def create
		@item = Item.new(item_params)

		if @item.save
			redirect_to @item
		else
			render 'new'
		end
	end
	def modif
		#puts " --------------------------------------------------------------------"
		#byebug
		@tmp =  Integer(params[:item][:stock])
		@item = Item.find(params[:id])
		if @item.update_attribute(:stock, @item.stock+@tmp)
			#@item.stock = @items
			redirect_to @item
		else
			render 'modify'
		end
	end
	def update
		@item = Item.find(params[:id])

		if @item.update(item_params)
			redirect_to @item
		else
			render 'edit'
		end
	end
	
	def destroy
		@item = Item.find(params[:id])
		@item.destroy

		redirect_to items_path
	end
	private
		def item_params
			params.require(:item).permit(:ino,:name,:price,:stock)
		end
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item,
local: true do |form| %>
<% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %> prohibited
        this item from being saved:
      </h2>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :ino %><br>
    <%= form.text_field :ino %>
  </p>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
 <p>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </p>

  <p>
    <%= form.label :stock %><br>
    <%= form.text_field :stock %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/items/edit.html.erb
<h1>Edit items details</h1>
 
<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing Item Details</h1>
 
<%= link_to 'New Item', new_item_path %>
<%= link_to 'HOME', welcome_index_path %>
<table>
  <tr>
    <th>ino</th>
    <th>name</th>
    <th>price</th>
    <th>stock</th>
    <th></th>
  </tr>
 
  <% @item.each do |item| %>
    <tr>
      <td><%= item.ino %></td>
      <td><%= item.name %></td>
      <td><%= item.price %></td>
      <td><%= item.stock %></td>
      <td><%= link_to 'Show', item_path(item) %></td>
      <td><%= link_to 'Edit', edit_item_path(item) %>
      <td><%= link_to 'Destroy', item_path(item),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Add-Stock', modify_item_path(item) %></td>

    </tr>
  <% end %>
</table>

app/views/items/modify.html.erb
<%= form_for @item, :url => url_for(:controller => 'items', :action => 'modif') do |form| %>
<% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %> prohibited
        this item from being saved:
      </h2>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<p>
    <%= form.label :stock %><br>
    <%= form.text_field :stock %>
  </p>
  <p>
    <%= form.submit('Modify stock') %>
  </p>
<% end%>
<%= link_to 'Back', items_path %>
  

app/views/items/new.html.erb
<h1>New Item</h1>
 
<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>item no:</strong>
  <%= @item.ino %>
</p>
 
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>price of item :</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Stock availability:</strong>
  <%= @item.stock %>
</p>
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %> |
<%= link_to 'HOME', welcome_index_path %>